config/routes.rb
Rails.application.routes.draw do

  resources :facilities
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/facility.rb
class Facility < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :find_facility, only: [:show, :update, :edit, :destroy]

  def new
    @facility = Facility.new
  end

  def create
    @facility = Facility.new(facility_params)

    if @facility.save
      redirect_to @facility
    else
      render new
    end
  end

  def show
  end

  def update
    if @facility.update(facility_params)
      redirect_to @facility
    else
      render 'edit'
    end
    
  end

  def edit
  end

  def destroy
    @facility.destroy
    redirect_to facilities_path
  end

  def index
    @facilities = Facility.all.order("created_at DESC")
  end


  private

  def facility_params
    params.require(:facility).permit(:name, :description, :status)
  end

  def find_facility
    @facility = Facility.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/facilities/edit.html.erb
<div class="container">
  <%= simple_form_for @facility do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :status %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/facilities/index.html.erb
<section class="section">
  <div class="container">
    <% if @facilities.count != 0 %>
      <% @facilities.each do |facility| %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4">
                <%= link_to facility.name, facility %>
              </p>
            </div>
          </div>
          <div class="content">
            <h2>
            <%= facility.description %>
          </h2>
          </div>
          <!-- <div class="comment-count">
              <span class="tag is-rounded">
                <%  # Comment count%>
              </span>
            </div> -->
        </div>
      </div>
      <% end %>
    <% else %>
      <h1>No Facilities</h1>  
    <% end %>
  </div>
</section>

app/views/facilities/new.html.erb
<div class="container">
  <%= simple_form_for @facility do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :status %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/facilities/show.html.erb
<div class="container">
  <h2>
    <%= @facility.name %>
  </h2>
  <h3>
    <%= @facility.description %>
  </h3>
  <h4>
    <%= @facility.status %>
  </h4>
  <%= link_to "Edit", edit_facility_path(@facility), class: "btn btn-primary" %>
  <%= link_to "Delete", facility_path(@facility), method: :delete, data: { confirm: "Are you sure? "},class: "btn btn-danger" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to PUPSJ Online Facility and Equipment Reservation System</h1>
<p>Find me in app/views/pages/index.html.erb</p>